import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import anchorPkg from "@coral-xyz/anchor";
const { AnchorProvider, Wallet, BN } = anchorPkg;
import { TensorSwapSDK } from "@tensor-oss/tensorswap-sdk";
import { getAssociatedTokenAddressSync } from "@solana/spl-token";
import bs58 from "bs58";
import dotenv from "dotenv";

dotenv.config();

// ==============================================================================
// CONFIGURATION
// ==============================================================================
// Replace this with the Mint Address of the NFT you want to list
const NFT_MINT_ADDRESS = "BE7w4LRBwG3AMo4NSv4oyFAF2xroHdEuY6gqjdQYWXmG";

// Set your listing price in SOL
const LISTING_PRICE_SOL = 1.5; 

// Connection to Solana Devnet since you are testing
const SOLANA_RPC_URL = process.env.SOLANA_RPC_URL || "https://api.devnet.solana.com";
// ==============================================================================

async function main() {
    console.log(`Starting Tensor Listing Script...`);

    // 1. Initialize Wallet and Connection
    let secretKey;
    const secretKeyString = process.env.SOLANA_PRIVATE_KEY;
    
    if (secretKeyString) {
        secretKey = bs58.decode(secretKeyString);
    } else {
        // Fallback to Solana CLI default path
        const fs = await import("fs");
        const path = await import("path");
        const os = await import("os");
        const keypairPath = path.join(os.homedir(), ".config", "solana", "id.json");
        if (fs.existsSync(keypairPath)) {
            const keypairData = JSON.parse(fs.readFileSync(keypairPath, "utf-8"));
            secretKey = new Uint8Array(keypairData);
        } else {
            throw new Error("Missing SOLANA_PRIVATE_KEY in .env file and no CLI keypair found.");
        }
    }

    const keypair = Keypair.fromSecretKey(secretKey);
    const wallet = new Wallet(keypair);
    
    console.log(`Wallet Address: ${wallet.publicKey.toBase58()}`);

    const connection = new Connection(SOLANA_RPC_URL, "confirmed");
    const provider = new AnchorProvider(connection, wallet, {
        preflightCommitment: "confirmed",
    });

    // 2. Initialize TensorSwap SDK
    const swapSdk = new TensorSwapSDK({ provider });

    // 3. Prepare Accounts for Listing
    const nftMint = new PublicKey(NFT_MINT_ADDRESS);
    
    // Find the associated token account for your wallet and this NFT
    const nftSellerAcc = getAssociatedTokenAddressSync(
        nftMint,
        wallet.publicKey
    );

    // Convert price to Lamports (1 SOL = 1,000,000,000 Lamports)
    const priceLamports = new BN(LISTING_PRICE_SOL * 1e9);

    console.log(`Preparing to list NFT: ${NFT_MINT_ADDRESS}`);
    console.log(`Token Account: ${nftSellerAcc.toBase58()}`);
    console.log(`Price: ${LISTING_PRICE_SOL} SOL`);

    try {
        // 4. Generate the Listing Transaction
        const { tx } = await swapSdk.list({
            nftMint,
            nftSellerAcc,
            owner: wallet.publicKey,
            price: priceLamports,
        });

        // The SDK returns a `TransactionEnvelope` or similar structure containing the ixs
        // Depending on SDK version, it could be `tx.ixs` or `tx.instructions`
        const ixs = tx.ixs || tx.instructions;

        if (!ixs || ixs.length === 0) {
            throw new Error("No instructions generated by the SDK");
        }

        const transaction = new provider.connection.Transaction().add(...ixs);
        transaction.feePayer = wallet.publicKey;
        transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;

        // 5. Sign and Send
        console.log("Signing and sending transaction...");
        const signature = await provider.wallet.signTransaction(transaction);
        const txId = await connection.sendRawTransaction(signature.serialize());

        console.log(`\n✅ Successfully listed NFT on Tensor!`);
        console.log(`View Transaction: https://solscan.io/tx/${txId}`);

    } catch (error) {
        console.error("\n❌ Error during listing:");
        console.error(error.message || error);
    }
}

main().catch(console.error);
